name: "Ostad Workflow CI/CD Pipeline"
on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
jobs:
  read_the_file:
    runs-on: ubuntu-latest

    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v6
      - name: Node version check
        run: node -v
      - name: Install dependencies
        run: npm install
      - name: bild the project
        run: npm run build
      - name: pm2 install
        run: npm install pm2 -g
      - name: pm2 start
        run: pm2 start npm --name "ostad-app" -- run dev
      - name: read the file
        run: cat hanif.txt