name: "Ostad Workflow CI/CD Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main.

jobs:
  Setup_Nginx:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nginx
        run: sudo apt-get update && sudo apt-get install -y nginx