name: "Ostad Workflow CI/CD Pipeline"
on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
jobs:
  read_the_file:
    runs-on: self-hosted

    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v6
      - name: Node version check
        run: node -v
      - name: Install PM2
        run: npm install -g pm2

      - name: Start app with PM2
        run: pm2 start npm --name "ostad-app" -- run start

      - name: Read file
        run: cat hanif.txt
